#!/bin/bash

### 在用户安装应用程序之前调用此脚本。
# 确保路径存在(因为卸载时删除了该目录，重新安装该目录不会自动创建)
LOG_FILE=/var/log/rtp2http.log

mkdir -p "$TRIM_PKGETC"
mkdir -p "$TRIM_PKGHOME"

# 初始化配置文件
echo "$(date '+%Y-%m-%d %H:%M:%S') - [install_init] Config file path: ${TRIM_PKGETC}/rtp2httpd.conf" >> "$LOG_FILE"
{
  echo "[global]"
  echo "verbosity = 2"
  echo "maxclients = 20"
  echo "udpxy = ${wizard_udpxy:-yes}"
  echo "workers = 1"
  echo "status-page-path = /status"
  echo "player-page-path = /player"
  echo "upstream-interface = ${wizard_upstream_interface:-enp2s0}"
  echo "external-m3u = file://${TRIM_PKGHOME}/player-list.m3u"
  echo "external-m3u-update-interval = 7200"
  echo "fcc-listen-port-range = 40000-40100"
  echo "buffer-pool-max-size = 163840"

  echo "[bind]"
  echo "* ${wizard_port:-5140}"
} >${TRIM_PKGETC}/rtp2httpd.conf

# 初始化本地直播流m3u文件
echo "$(date '+%Y-%m-%d %H:%M:%S') - [install_init] Init local m3u file: ${TRIM_PKGHOME}/player-list.m3u" >> "$LOG_FILE"
cp "${TRIM_PKGINST_TEMP_DIR}/server/player-list.m3u" ${TRIM_PKGHOME}

exit 0
