#!/bin/bash

LOG_FILE="${TRIM_PKGVAR}/info.log"
PID_FILE="${TRIM_PKGVAR}/app.pid"
CONF_FILE="${TRIM_PKGETC}/rtp2httpd.conf"

# 写入程序启动命令
CMD="${TRIM_APPDEST}/server/rtp2httpd --config ${CONF_FILE}"

log_msg() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >> ${LOG_FILE}
}

start_process() {
    if status; then
        return 0
    fi

    log_msg "Starting process ..."
    # 运行程序
    bash -c "${CMD}" >> ${LOG_FILE} 2>&1 &
    # 写入 pid 到文件
    printf "%s" "$!" > ${PID_FILE}

    return 0
}

stop_process() {
    # 停止程序
    log_msg "Stopping process ..."
    if [ -r "${PID_FILE}" ]; then
        pid=$(head -n 1 "${PID_FILE}" | tr -d '[:space:]')

        # 获取 pid
        log_msg "pid=${pid}"
        if ! check_process "${pid}"; then
            # 程序不存在，删除 pid 文件
            rm -f "${PID_FILE}"
            log_msg "remove pid file 1"
            return
        fi

        log_msg "send TERM signal to PID:${pid}..."
        kill -TERM ${pid} >> ${LOG_FILE} 2>&1

        # 等待程序退出
        local count=0
        while check_process "${pid}" && [ $count -lt 10 ]; do
            sleep 1
            count=$((count + 1))
            log_msg "waiting process terminal... (${count}s/10s)"
        done

        if check_process "${pid}"; then
            log_msg "send KILL signal to PID:${pid}..."
            kill -KILL "${pid}"
            sleep 1
            rm -f "${PID_FILE}"
        else
            log_msg "process killed... "
        fi
    fi

    return 0
}

check_process() {
    local pid=$1
    if kill -0 "${pid}" 2>/dev/null; then
        return 0
    else
        return 1
    fi
}

status() {
    if [ -f "${PID_FILE}" ]; then
        pid=$(head -n 1 "${PID_FILE}" | tr -d '[:space:]')
        if check_process "${pid}"; then
            return 0
        else
            # 进程没有运行，pid 文件存在，则删除
            rm -f "${PID_FILE}"
        fi
    fi

    return 1
}

case $1 in
start)
    # 运行启动命令。成功则退出0，失败则退出1
    start_process
    ;;
stop)
    # 运行停止命令。成功则退出0，失败则退出1
    stop_process
    ;;
status)
    # 检查应用程序状态命令。如果运行则退出 0，如果不运行则退出 3
    if status; then
        exit 0
    else
        exit 3
    fi
    ;;
*)
    exit 1
    ;;
esac
