#!/bin/bash

### 该脚本在用户卸载应用程序后被调用。
LOG_FILE="${TRIM_PKGVAR}/script.log"

echo "$(date '+%Y-%m-%d %H:%M:%S') - [uninstall_callback] 该脚本在用户卸载应用程序后被调用" >> "$LOG_FILE"
echo "$(date '+%Y-%m-%d %H:%M:%S') - [uninstall_callback] 用户卸载应用，数据保留选项为：${wizard_data_action:-}" >> "$LOG_FILE"
if [ "${wizard_data_action:-}" == "delete" ]; then
  echo "$(date '+%Y-%m-%d %H:%M:%S') - [uninstall_callback] 开始删除用户数据" >> "$LOG_FILE"
  rm -rf ${TRIM_PKGETC}
  rm -rf ${TRIM_PKGMETA}
  rm -rf ${TRIM_PKGHOME}
  rm -rf ${TRIM_PKGVAR}
  IFS=':'; for p in $TRIM_DATA_SHARE_PATHS; do [ -e "$p" ] && rm -rf "$p"; done
fi

exit 0
